algoritmo "Somador 2"

var
N4,N5:Inteiro

Procedimento Soma2(var Z,K:Inteiro)
Inicio
      Z<-Z+1
      K<-K+2
      Escreval("O valor de Z é ",Z)
      Escreval("O valor de K é ",K)
      Escreval("A soma entre os valores é ",Z+K)
FimProcedimento

inicio
Escreval("-------------------------")
Escreval("        Somador 2        ")
Escreval("-------------------------")
N4<-8
N5<-5
Soma2(N4,N5)
Escreval("O valor de N4 é ",N4)
Escreval("O valor de N5 é ",N5)
fimalgoritmo
