algoritmo "Contagem Opcional"

var
Contador,Valor,Salto:Inteiro

inicio
Escreval("--------------------")
Escreval("  Contagem Opcional ")
Escreval("--------------------")
Escreval("Quer contar até quanto? ")
Leia(Valor)
Escreval("Quantos Saltos? ")
Leia(Salto)
Contador<-0
Enquanto (Contador<=Valor)faca
         Escreval(Contador)
         Contador<-Contador+Salto
FimEnquanto
Escreval("Fim de contar")
Escreval("--------------------")
fimalgoritmo
